LOGIN_ACCESS_TIME = 5
LOGIN_FORBIDDEN_TIME = 600  # unit: s

AREA_CACHE_EXPIRE_TIME = 7200
FACILITY_CACHE_EXPIRE_TIME = 7200
HOME_PAGE_DATA_REDIS_EXPIRES = 7200
HOUSE_LIST_REDIS_EXPIRES = 7200
HOUSE_DETAIL_REDIS_EXPIRES = 7200

ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png'}
AWS_IMAGE_PREFIX = "https://rental-rental.s3.amazonaws.com/"
REDIS_HOUSE_LIST_PREFIX = "house_list_"
REDIS_HOUSE_PREFIX = "house_"

HOME_PAGE_MAX_HOUSES = 5

SORT_OPTIONS = {"0": "newest", "1": "popularity", "2": "price-asc", "3": "price-desc"}
HOUSE_LIST_PAGE_SIZE = 3
HOUSE_DETAIL_COMMENT_DISPLAY_COUNTS = 5

SENDER_EMAIL = "luoyifu25@gmail.com"
